In [25]:
import pandas as pd

# Load the dataset
file_path = "Manufacturing_Dataset.csv"  # Replace with your CSV file path
df = pd.read_csv(file_path)

# Analyze missing values
missing_values = df.isnull().sum()
print("missing_values")
print(missing_values)

missing_values
Production ID                       0
Date                                0
Product Type                        0
Machine ID                          0
Shift                               0
Units Produced                      0
Defects                           299
Production Time Hours               0
Material Cost Per Unit              0
Labour Cost Per Hour                0
Energy Consumption kWh              0
Operator Count                      0
Maintenance Hours                 300
Down time Hours                   300
Production Volume Cubic Meters      0
Scrap Rate                          0
Rework Hours                      300
Quality Checks Failed               0
Average Temperature C               0
Average Humidity Percent            0
dtype: int64

In [27]:
print(" len(df)")
print(len(df))

 len(df)
3000

In [31]:
missing_percentage = (missing_values / len(df)) * 100
print(f"Missing Percentage:\n{missing_percentage}")

Missing Percentage:
Production ID                      0.000000
Date                               0.000000
Product Type                       0.000000
Machine ID                         0.000000
Shift                              0.000000
Units Produced                     0.000000
Defects                            9.966667
Production Time Hours              0.000000
Material Cost Per Unit             0.000000
Labour Cost Per Hour               0.000000
Energy Consumption kWh             0.000000
Operator Count                     0.000000
Maintenance Hours                 10.000000
Down time Hours                   10.000000
Production Volume Cubic Meters     0.000000
Scrap Rate                         0.000000
Rework Hours                      10.000000
Quality Checks Failed              0.000000
Average Temperature C              0.000000
Average Humidity Percent           0.000000
dtype: float64

In [35]:
pd.DataFrame({"Column": df.columns,
    "Missing Values": missing_values,
    "Percentage Missing (%)": missing_percentage
}).sort_values(by="Percentage Missing (%)",  ascending=False)

,Column,Missing Values,Percentage Missing (%)
Rework Hours,Rework Hours,300,10.000000
Down time Hours,Down time Hours,300,10.000000
Maintenance Hours,Maintenance Hours,300,10.000000
Defects,Defects,299,9.966667
Production ID,Production ID,0,0.000000
Operator Count,Operator Count,0,0.000000
Average Temperature C,Average Temperature C,0,0.000000
Quality Checks Failed,Quality Checks Failed,0,0.000000
Scrap Rate,Scrap Rate,0,0.000000
Production Volume Cubic Meters,Production Volume Cubic Meters,0,0.000000
Energy Consumption kWh,Energy Consumption kWh,0,0.000000
Date,Date,0,0.000000
Labour Cost Per Hour,Labour Cost Per Hour,0,0.000000
Material Cost Per Unit,Material Cost Per Unit,0,0.000000
Production Time Hours,Production Time Hours,0,0.000000
Units Produced,Units Produced,0,0.000000
Shift,Shift,0,0.000000
Machine ID,Machine ID,0,0.000000
Product Type,Product Type,0,0.000000
Average Humidity Percent,Average Humidity Percent,0,0.000000

In [37]:
# Handle missing values
for col in df.columns:
    if df[col].isnull().sum() > 0:
        if df[col].dtype in ['float64', 'int64']:  # Numerical column
            df[col].fillna(df[col].mean(), inplace=True)
        else:  # Categorical column
            df[col].fillna(df[col].mode()[0], inplace=True)

# Save the imputed dataset
df.to_csv("imputed_data.csv", index=False)

print("\nMissing values imputed and saved to 'imputed_data.csv'.")

Missing values imputed and saved to 'imputed_data.csv'.

C:\Users\kanak\AppData\Local\Temp\ipykernel_32780\3955665500.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mean(), inplace=True)