In [5]:
# Import libraries

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score

# Load dataset
data = pd.read_csv('Healthcare_Data_Preprocessed.csv')

In [7]:
# Explore data
print(data.info())
print(data.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Age                   10000 non-null  float64
 1   BMI                   10000 non-null  float64
 2   Blood_Pressure        10000 non-null  float64
 3   Cholesterol           10000 non-null  float64
 4   Glucose_Level         10000 non-null  float64
 5   Heart_Rate            10000 non-null  float64
 6   Sleep_Hours           10000 non-null  float64
 7   Exercise_Hours        10000 non-null  float64
 8   Water_Intake          10000 non-null  float64
 9   Stress_Level          10000 non-null  float64
 10  Target                10000 non-null  int64
 11  Smoking               10000 non-null  int64
 12  Alcohol               10000 non-null  int64
 13  Diet                  10000 non-null  int64
 14  MentalHealth          10000 non-null  int64
 15  PhysicalActivity      10000 non-null  int64
 16  MedicalHistory        10000 non-null  int64
 17  Allergies             10000 non-null  int64
 18  Diet_Type_Vegan       10000 non-null  bool
 19  Diet_Type_Vegetarian  10000 non-null  bool
 20  Blood_Group_AB        10000 non-null  bool
 21  Blood_Group_B         10000 non-null  bool
 22  Blood_Group_O         10000 non-null  bool
dtypes: bool(5), float64(10), int64(8)
memory usage: 1.4 MB
None
                Age           BMI  Blood_Pressure   Cholesterol  \
count  10000.000000  10000.000000    10000.000000  10000.000000
mean      40.228000     25.711500      131.027300    199.252100
std       24.350238      1.944594       27.631176      2.105941
min        0.000000     19.000000       22.000000    192.000000
25%       25.000000     24.000000      115.000000    198.000000
50%       37.000000     26.000000      135.000000    199.000000
75%       49.000000     27.000000      150.000000    201.000000
max      100.000000     32.000000      225.000000    207.000000

       Glucose_Level    Heart_Rate   Sleep_Hours  Exercise_Hours  \
count   10000.000000  10000.000000  10000.000000    10000.000000
mean      100.115700     73.531400     41.344000       41.344000
std         2.211471      1.724329     27.791396       27.791396
min        93.000000     67.000000      0.000000        0.000000
25%        99.000000     72.000000     25.000000       25.000000
50%       100.000000     74.000000     37.000000       37.000000
75%       102.000000     75.000000     49.000000       49.000000
max       107.000000     80.000000    201.000000      201.000000

       Water_Intake  Stress_Level        Target       Smoking       Alcohol  \
count  10000.000000  10000.000000  10000.000000  10000.000000  10000.000000
mean      41.344000     41.344000      0.499900      0.994500      0.992700
std       27.791396     27.791396      0.500025      0.815681      0.816525
min        0.000000      0.000000      0.000000      0.000000      0.000000
25%       25.000000     25.000000      0.000000      0.000000      0.000000
50%       37.000000     37.000000      0.000000      1.000000      1.000000
75%       49.000000     49.000000      1.000000      2.000000      2.000000
max      201.000000    201.000000      1.000000      2.000000      2.000000

               Diet  MentalHealth  PhysicalActivity  MedicalHistory  \
count  10000.000000   10000.00000      10000.000000     10000.00000
mean       1.005500       0.99670          1.000600         1.00190
std        0.816172       0.82326          0.809979         0.81398
min        0.000000       0.00000          0.000000         0.00000
25%        0.000000       0.00000          0.000000         0.00000
50%        1.000000       1.00000          1.000000         1.00000
75%        2.000000       2.00000          2.000000         2.00000
max        2.000000       2.00000          2.000000         2.00000

          Allergies
count  10000.000000
mean       0.993100
std        0.816284
min        0.000000
25%        0.000000
50%        1.000000
75%        2.000000
max        2.000000

In [13]:

print(data)
# Handle missing values
data.fillna(data.median(), inplace=True)

       Age   BMI  Blood_Pressure  Cholesterol  Glucose_Level  Heart_Rate  \
0     37.0  26.0           111.0        198.0           99.0        72.0
1     37.0  24.0           121.0        199.0          103.0        75.0
2     81.0  27.0           147.0        203.0          100.0        74.0
3     25.0  21.0           150.0        199.0          102.0        70.0
4     24.0  26.0           146.0        202.0           99.0        76.0
...    ...   ...             ...          ...            ...         ...
9995   5.0  22.0           109.0        203.0           98.0        75.0
9996  94.0  26.0           144.0        203.0           96.0        72.0
9997  37.0  23.0           185.0        198.0          103.0        72.0
9998  50.0  29.0           166.0        200.0          100.0        74.0
9999  69.0  29.0           178.0        203.0          100.0        75.0

      Sleep_Hours  Exercise_Hours  Water_Intake  Stress_Level  ...  Diet  \
0            37.0            37.0          37.0          37.0  ...     1
1            37.0            37.0          37.0          37.0  ...     1
2            81.0            81.0          81.0          81.0  ...     2
3            25.0            25.0          25.0          25.0  ...     1
4            24.0            24.0          24.0          24.0  ...     2
...           ...             ...           ...           ...  ...   ...
9995          5.0             5.0           5.0           5.0  ...     0
9996         94.0            94.0          94.0          94.0  ...     1
9997         37.0            37.0          37.0          37.0  ...     1
9998         50.0            50.0          50.0          50.0  ...     2
9999         69.0            69.0          69.0          69.0  ...     1

      MentalHealth  PhysicalActivity  MedicalHistory  Allergies  \
0                2                 1               0          1
1                2                 1               2          2
2                0                 0               1          0
3                2                 1               2          0
4                0                 2               0          2
...            ...               ...             ...        ...
9995             2                 2               1          0
9996             0                 1               0          2
9997             0                 2               0          1
9998             0                 0               1          1
9999             2                 1               2          0

      Diet_Type_Vegan  Diet_Type_Vegetarian  Blood_Group_AB  Blood_Group_B  \
0               False                  True            True          False
1               False                 False            True          False
2                True                 False           False          False
3                True                 False           False           True
4               False                  True           False           True
...               ...                   ...             ...            ...
9995             True                 False            True          False
9996            False                  True           False           True
9997             True                 False            True          False
9998             True                 False            True          False
9999            False                 False            True          False

      Blood_Group_O
0             False
1             False
2             False
3             False
4             False
...             ...
9995          False
9996          False
9997          False
9998          False
9999          False

[10000 rows x 23 columns]

In [11]:
print(data)

       Age   BMI  Blood_Pressure  Cholesterol  Glucose_Level  Heart_Rate  \
0     37.0  26.0           111.0        198.0           99.0        72.0
1     37.0  24.0           121.0        199.0          103.0        75.0
2     81.0  27.0           147.0        203.0          100.0        74.0
3     25.0  21.0           150.0        199.0          102.0        70.0
4     24.0  26.0           146.0        202.0           99.0        76.0
...    ...   ...             ...          ...            ...         ...
9995   5.0  22.0           109.0        203.0           98.0        75.0
9996  94.0  26.0           144.0        203.0           96.0        72.0
9997  37.0  23.0           185.0        198.0          103.0        72.0
9998  50.0  29.0           166.0        200.0          100.0        74.0
9999  69.0  29.0           178.0        203.0          100.0        75.0

      Sleep_Hours  Exercise_Hours  Water_Intake  Stress_Level  ...  Diet  \
0            37.0            37.0          37.0          37.0  ...     1
1            37.0            37.0          37.0          37.0  ...     1
2            81.0            81.0          81.0          81.0  ...     2
3            25.0            25.0          25.0          25.0  ...     1
4            24.0            24.0          24.0          24.0  ...     2
...           ...             ...           ...           ...  ...   ...
9995          5.0             5.0           5.0           5.0  ...     0
9996         94.0            94.0          94.0          94.0  ...     1
9997         37.0            37.0          37.0          37.0  ...     1
9998         50.0            50.0          50.0          50.0  ...     2
9999         69.0            69.0          69.0          69.0  ...     1

      MentalHealth  PhysicalActivity  MedicalHistory  Allergies  \
0                2                 1               0          1
1                2                 1               2          2
2                0                 0               1          0
3                2                 1               2          0
4                0                 2               0          2
...            ...               ...             ...        ...
9995             2                 2               1          0
9996             0                 1               0          2
9997             0                 2               0          1
9998             0                 0               1          1
9999             2                 1               2          0

      Diet_Type_Vegan  Diet_Type_Vegetarian  Blood_Group_AB  Blood_Group_B  \
0               False                  True            True          False
1               False                 False            True          False
2                True                 False           False          False
3                True                 False           False           True
4               False                  True           False           True
...               ...                   ...             ...            ...
9995             True                 False            True          False
9996            False                  True           False           True
9997             True                 False            True          False
9998             True                 False            True          False
9999            False                 False            True          False

      Blood_Group_O
0             False
1             False
2             False
3             False
4             False
...             ...
9995          False
9996          False
9997          False
9998          False
9999          False

[10000 rows x 23 columns]

In [22]:
# Handle missing values
data.fillna(data.median(), inplace=True)

In [24]:
print(data)

       Age   BMI  Blood_Pressure  Cholesterol  Glucose_Level  Heart_Rate  \
0     37.0  26.0           111.0        198.0           99.0        72.0
1     37.0  24.0           121.0        199.0          103.0        75.0
2     81.0  27.0           147.0        203.0          100.0        74.0
3     25.0  21.0           150.0        199.0          102.0        70.0
4     24.0  26.0           146.0        202.0           99.0        76.0
...    ...   ...             ...          ...            ...         ...
9995   5.0  22.0           109.0        203.0           98.0        75.0
9996  94.0  26.0           144.0        203.0           96.0        72.0
9997  37.0  23.0           185.0        198.0          103.0        72.0
9998  50.0  29.0           166.0        200.0          100.0        74.0
9999  69.0  29.0           178.0        203.0          100.0        75.0

      Sleep_Hours  Exercise_Hours  Water_Intake  Stress_Level  ...  Diet  \
0            37.0            37.0          37.0          37.0  ...     1
1            37.0            37.0          37.0          37.0  ...     1
2            81.0            81.0          81.0          81.0  ...     2
3            25.0            25.0          25.0          25.0  ...     1
4            24.0            24.0          24.0          24.0  ...     2
...           ...             ...           ...           ...  ...   ...
9995          5.0             5.0           5.0           5.0  ...     0
9996         94.0            94.0          94.0          94.0  ...     1
9997         37.0            37.0          37.0          37.0  ...     1
9998         50.0            50.0          50.0          50.0  ...     2
9999         69.0            69.0          69.0          69.0  ...     1

      MentalHealth  PhysicalActivity  MedicalHistory  Allergies  \
0                2                 1               0          1
1                2                 1               2          2
2                0                 0               1          0
3                2                 1               2          0
4                0                 2               0          2
...            ...               ...             ...        ...
9995             2                 2               1          0
9996             0                 1               0          2
9997             0                 2               0          1
9998             0                 0               1          1
9999             2                 1               2          0

      Diet_Type_Vegan  Diet_Type_Vegetarian  Blood_Group_AB  Blood_Group_B  \
0               False                  True            True          False
1               False                 False            True          False
2                True                 False           False          False
3                True                 False           False           True
4               False                  True           False           True
...               ...                   ...             ...            ...
9995             True                 False            True          False
9996            False                  True           False           True
9997             True                 False            True          False
9998             True                 False            True          False
9999            False                 False            True          False

      Blood_Group_O
0             False
1             False
2             False
3             False
4             False
...             ...
9995          False
9996          False
9997          False
9998          False
9999          False

[10000 rows x 23 columns]

In [29]:
# Correct negative age values
data['Age'] = data['Age'].apply(lambda x: abs(x) if x < 0 else x)
print(data)

       Age   BMI  Blood_Pressure  Cholesterol  Glucose_Level  Heart_Rate  \
0     37.0  26.0           111.0        198.0           99.0        72.0
1     37.0  24.0           121.0        199.0          103.0        75.0
2     81.0  27.0           147.0        203.0          100.0        74.0
3     25.0  21.0           150.0        199.0          102.0        70.0
4     24.0  26.0           146.0        202.0           99.0        76.0
...    ...   ...             ...          ...            ...         ...
9995   5.0  22.0           109.0        203.0           98.0        75.0
9996  94.0  26.0           144.0        203.0           96.0        72.0
9997  37.0  23.0           185.0        198.0          103.0        72.0
9998  50.0  29.0           166.0        200.0          100.0        74.0
9999  69.0  29.0           178.0        203.0          100.0        75.0

      Sleep_Hours  Exercise_Hours  Water_Intake  Stress_Level  ...  Diet  \
0            37.0            37.0          37.0          37.0  ...     1
1            37.0            37.0          37.0          37.0  ...     1
2            81.0            81.0          81.0          81.0  ...     2
3            25.0            25.0          25.0          25.0  ...     1
4            24.0            24.0          24.0          24.0  ...     2
...           ...             ...           ...           ...  ...   ...
9995          5.0             5.0           5.0           5.0  ...     0
9996         94.0            94.0          94.0          94.0  ...     1
9997         37.0            37.0          37.0          37.0  ...     1
9998         50.0            50.0          50.0          50.0  ...     2
9999         69.0            69.0          69.0          69.0  ...     1

      MentalHealth  PhysicalActivity  MedicalHistory  Allergies  \
0                2                 1               0          1
1                2                 1               2          2
2                0                 0               1          0
3                2                 1               2          0
4                0                 2               0          2
...            ...               ...             ...        ...
9995             2                 2               1          0
9996             0                 1               0          2
9997             0                 2               0          1
9998             0                 0               1          1
9999             2                 1               2          0

      Diet_Type_Vegan  Diet_Type_Vegetarian  Blood_Group_AB  Blood_Group_B  \
0               False                  True            True          False
1               False                 False            True          False
2                True                 False           False          False
3                True                 False           False           True
4               False                  True           False           True
...               ...                   ...             ...            ...
9995             True                 False            True          False
9996            False                  True           False           True
9997             True                 False            True          False
9998             True                 False            True          False
9999            False                 False            True          False

      Blood_Group_O
0             False
1             False
2             False
3             False
4             False
...             ...
9995          False
9996          False
9997          False
9998          False
9999          False

[10000 rows x 23 columns]

In [37]:
le = LabelEncoder()

In [43]:
for col in ['Diet_Type_Vegan', 'Blood_Group_AB']:  # Adjusted column name
    data[col] = le.fit_transform(data[col])

In [49]:
# Feature scaling
scaler = StandardScaler()
numerical_cols = ['BMI', 'Blood_Pressure', 'Cholesterol', 'Glucose_Level', 'Heart_Rate', 'Sleep_Hours', 'Exercise_Hours']
data[numerical_cols] = scaler.fit_transform(data[numerical_cols])
print(data[numerical_cols])

           BMI  Blood_Pressure  Cholesterol  Glucose_Level  Heart_Rate  \
0     0.148367       -0.724844    -0.594586      -0.504531   -0.888158
1    -0.880176       -0.362916    -0.119715       1.304310    0.851736
2     0.662639        0.578097     1.779768      -0.052321    0.271771
3    -2.422992        0.686675    -0.119715       0.852100   -2.048087
4     0.148367        0.541904     1.304897      -0.504531    1.431701
...        ...             ...          ...            ...         ...
9995 -1.908720       -0.797230     1.779768      -0.956742    0.851736
9996  0.148367        0.469519     1.779768      -1.861162   -0.888158
9997 -1.394448        1.953424    -0.594586       1.304310   -0.888158
9998  1.691183        1.265760     0.355156      -0.052321    0.271771
9999  1.691183        1.700074     1.779768      -0.052321    0.851736

      Sleep_Hours  Exercise_Hours
0       -0.156315       -0.156315
1       -0.156315       -0.156315
2        1.426988        1.426988
3       -0.588125       -0.588125
4       -0.624109       -0.624109
...           ...             ...
9995    -1.307808       -1.307808
9996     1.894782        1.894782
9997    -0.156315       -0.156315
9998     0.311479        0.311479
9999     0.995178        0.995178

[10000 rows x 7 columns]

In [51]:
# Split data into features and target
X = data.drop(columns=['Target'])
y = data['Target']

In [53]:
# Split into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train a model
model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)

# Evaluate the model
y_pred = model.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(f"ROC-AUC Score: {roc_auc_score(y_test, y_pred)}")

[[877 130]
 [115 878]]
              precision    recall  f1-score   support

           0       0.88      0.87      0.88      1007
           1       0.87      0.88      0.88       993

    accuracy                           0.88      2000
   macro avg       0.88      0.88      0.88      2000
weighted avg       0.88      0.88      0.88      2000

ROC-AUC Score: 0.8775464997784892